import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../common/components/Layout/Layout";
import { Home } from "../common/components/Home";

const Index: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </Layout>
  );
};

export default Index;
